version: "3.2"

services:
  vault:
    image: vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: supersecret
    cap_add:
      - IPC_LOCK
    expose:
      - 8200

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: supersecret
      DOMAIN: "${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vault
